#!/bin/bash                                                                  

# echo ($pacman -Qeq) > pacman-requirments.sh

sudo pacman -Syu \
    aarch64-linux-gnu-gcc \
    abook \
    acpi \
    ags-hyprpanel-git \
    alsa-utils \
    android-tools \
    anki \
    arduino-cli \
    arp-scan \
    asp \
    atool \
    base \
    base-devel \
    bat \
    bc \
    bear \
    blueman \
    bluez \
    bluez-utils \
    bridge-utils \
    brightnessctl \
    btop \
    cava \
    cbonsai \
    cheat \
    cliphist \
    clockify-cli \
    codelldb-bin \
    composer \
    cronie \
    cups \
    devtools \
    dibuja \
    discord \
    dnsmasq \
    docker \
    docker-buildx \
    docker-compose \
    docker-scout \
    dosfstools \
    dotnet-runtime \
    dotnet-sdk \
    doxygen \
    drawio-desktop \
    efibootmgr \
    exfat-utils \
    expac \
    eza \
    fd \
    ffmpeg4.4 \
    ffmpegthumbnailer \
    fzf \
    ghidra \
    ghostty \
    git \
    git-delta \
    git-filter-repo \
    github-cli \
    gitleaks \
    glow \
    gnome-keyring \
    go \
    grim \
    grub \
    gst-plugin-pipewire \
    gtk-theme-arc-gruvbox-git \
    gum \
    htop-vim \
    hypridle \
    hyprland \
    hyprlang \
    hyprlock \
    hyprpaper \
    hyprpicker \
    hyprshot-git \
    hyprwayland-scanner \
    ida-free \
    ifuse \
    imagemagick \
    inetutils \
    intel-ucode \
    itch-setup-bin \
    iw \
    jdk21-openjdk \
    jetbrains-toolbox \
    jmeter \
    jq \
    kitty \
    krabby-bin \
    lazygit \
    lf-git \
    lib32-vulkan-intel \
    libgccjit \
    linux \
    linux-firmware \
    linux-headers \
    ly \
    man-db \
    mariadb \
    masscan \
    mediainfo \
    minecraft-launcher \
    moreutils \
    mpc \
    mpd \
    mpv \
    multipath-tools \
    ncdu \
    ncmpcpp \
    neofetch \
    neovim \
    networkmanager \
    nmap \
    noto-fonts-cjk \
    npm \
    nsxiv \
    ntfs-3g \
    ntp \
    obsidian \
    ollama \
    onlyoffice-bin \
    openbsd-netcat \
    otf-libertinus \
    pacman-contrib \
    pandoc-cli \
    pavucontrol \
    php-apache \
    phpmyadmin \
    pipewire \
    pipewire-alsa \
    pipewire-jack \
    pipewire-pulse \
    plocate \
    power-profiles-daemon \
    progress \
    pulsemixer \
    pv \
    pyenv \
    python-matplotlib \
    python-pip \
    python-pipx \
    python-poetry \
    python-qdarkstyle \
    python-sphinx \
    python-tensorflow \
    qemu-base \
    qemu-emulators-full \
    qemu-user-static \
    ripgrep \
    rpi-imager \
    rpiusbboot \
    rt-tests \
    rustup \
    s-tui \
    sane \
    sc-im \
    screen \
    sdl3 \
    simple-mtpfs \
    slurp \
    socat \
    sof-firmware \
    speedtest-cli \
    spotify-launcher \
    starship \
    steam \
    stow \
    swaylock-effects-git \
    swaync \
    task-spooler \
    tesseract-data-eng \
    texlive-basic \
    texlive-latexextra \
    thefuck \
    tldr++ \
    tmux \
    torbrowser-launcher \
    traceroute \
    ttf-fira-code \
    ttf-font-awesome \
    tty-clock-git \
    tty-countdown-git \
    uboot-tools \
    ufw \
    unzip \
    upower \
    valgrind \
    vi \
    vim \
    virt-manager \
    virt-viewer \
    vulkan-intel \
    vulkan-tools \
    walker \
    wf-recorder \
    wget \
    wine \
    winetricks \
    wireplumber \
    wireshark-qt \
    wl-clipboard \
    wofi \
    wxwidgets-gtk3 \
    xcape \
    xdotool \
    xorg-server \
    xorg-xbacklight \
    xorg-xinit \
    xorg-xrandr \
    xorg-xsetroot \
    xorg-xwininfo \
    xsel \
    xwallpaper \
    xwayland-run \
    yarn \
    yay-bin \
    yazi \
    yt-dlp \
    zathura \
    zathura-pdf-mupdf \
    zen-browser-bin \
    zip \
    zoxide \
    zsh \
    zsh-fast-syntax-highlighting-git \
    zsh-syntax-highlighting
