
format = """
[](#ED8796)\
$os\
$username\
[](bg:#F5A97F fg:#ED8796)\
$directory\
[](fg:#F5A97F bg:#F2DFB7)\
$git_branch\
$git_status\
[](fg:#F2DFB7 bg:#A6DA95)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#A6DA95 bg:#7DC4E4)\
$docker_context\
[](fg:#7DC4E4 bg:#C6A0F6)\
$time\
[ ](fg:#C6A0F6)\
[ ]()
$character\
"""
[line_break]
disabled = true

[character]
# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#ED8796 fg:#4C4F69"
style_root = "bg:#ED8796 fg:#4C4F69"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#ED8796 fg:#4C4F69"
disabled = false # Disabled by default

[directory]
style = "bg:#F5A97F fg:#4C4F69"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#7DC4E4 fg:#4C4F69"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#F2DFB7 fg:#4C4F69"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F2DFB7 fg:#4C4F69"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#A6DA95 fg:#4C4F69"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C6A0F6 fg:#4C4F69"
format = '[ $time ]($style)'

